ALTER TABLE companies ADD COLUMN IF NOT EXISTS ticker TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS exchange TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS filer_category TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS total_assets BIGINT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS description TEXT;
